import { Theme } from '../types'

export const LightTheme: Theme = {
  //TODO in most cases palette need to be small
  //BACKGROUNDS

  bcColor_card: '#fff',
  bcColor_search: '#fff',
  bcColor_input: '#fff',
  bcColor_toast: '#000',
  bcColor_toast_error: '#ed1245',
  bcColor_tag: '#0a853760',
  bcColor_overlay: 'rgba(0, 0, 0, 0.5)',
  bcColor_layout: 'transparent',
  bcColor_label: '#fff',
  bcColor_button: '#fff',
  bcColor_btn_filled: '#0A8537',
  bcColor_btn_danger: '#850a0a',
  bcColor_standart_container: '#fff',
  bcColor_tabBar: '#fff',
  bcColor_event: '#0a8537',

  color_name: '#000',
  color_cross: '#000',
  color_standart_text: '#000',
  color_work_time: '#000',
  color_rounded_work: '#000000',
  borderColor_standart: '#000000',
  color_standart_work: '#6E6E77',
  color_toast_text: '#fff',
  color_input: '#000',
  color_fill_icon: '#000',
  color_search_icon: '#000',
  color_warn_icon: '#fff',
  color_calendar_icon: '#6E6E77',
  color_tag_icon: '#8E898A',
  color_filter_icon: '#000',
  color_edit_icon: '#0A8537',
  color_btn_filled: '#fff',
  color_btn_danger: '#fff',
  color_btn_picker: '#acacac',
  borderColor_tags: '#0a853760',
  borderColor_date_picker: '#acacac',
  color_standart_avatar: '#13d95c3d',
  color_section_title: '#6c6c6c',
  color_specialty: '#585455',
  color_standart_shadow: '#0A8537',
  borderColor_shadow: '#0000002c',
  borderTopColor_tabBar: '#6e6e7731',
  color_tabBar_active: '#0A8537',
  color_tabBar_inactive: '#6E6E77',
  borderColor_titleInput: '#48484866',
  color_titleInput: '#000',
  borderColor_searchHeader: '#6e6e7728',
  color_accentPicker: '#0A8537',
  color_weekDay: '#6E6E77',
  color_event: '#fff',
  color_linearGradient: '#fff',
}

export const DarkTheme: Theme = {
  //BACKGROUNDS
  bcColor_standart_container: '#191d20',
  bcColor_input: '#A6B2EC',
  bcColor_label: '#A6B2EC',
  bcColor_search: '#202020',
  bcColor_card: '#202020',
  bcColor_toast: '#000',
  bcColor_toast_error: '#ed1245',
  bcColor_tag: '#0a853760',
  bcColor_overlay: 'rgba(0, 0, 0, 0.5)',
  bcColor_layout: 'transparent',
  bcColor_button: '#191d20',
  bcColor_btn_filled: '#A6B2EC',
  bcColor_btn_danger: '#DA0038',
  bcColor_tabBar: '#191d20',
  bcColor_event: '#a6b1ec99',

  // color_standart_text: '#D2D2D2',
  color_standart_text: '#fff',
  color_input: '#000',
  borderColor_standart: '#fff',
  borderColor_searchHeader: '#A6B2EC',
  color_search_icon: '#fff',
  color_standart_shadow: '#fff',
  color_standart_avatar: '#A6B2EC',
  color_calendar_icon: '#E5E5E5',
  color_tag_icon: '#E5E5E5',
  color_name: '#D2D2D2',
  color_specialty: '#D2D2D2',
  borderColor_tags: '#D2D2D2',
  borderColor_titleInput: '#6c7883',
  color_titleInput: '#fff',
  color_cross: '#fff',
  color_work_time: '#fff',
  color_rounded_work: '#fff',
  color_standart_work: '#bec9d4',
  color_toast_text: '#fff',
  color_fill_icon: '#fff',
  color_warn_icon: '#fff',
  color_filter_icon: '#fff',
  color_edit_icon: '#0A8537',
  color_btn_filled: '#fff',
  color_btn_danger: '#fff',
  color_btn_picker: '#acacac',
  borderColor_date_picker: '#acacac',
  color_section_title: '#d1d1d3',
  borderColor_shadow: '#0000002c',
  borderTopColor_tabBar: '#fff',
  color_tabBar_active: '#A6B2EC',
  color_tabBar_inactive: '#D2D2D2',
  color_accentPicker: '#fff',
  color_weekDay: '#bec9d4',
  color_event: '#fff',
  color_linearGradient: '#191d20',
}
